version: '3'
services:
        proxy:
                container_name: proxy
                restart: always
                image: traefik:alpine
                command:
                        - "--api"
                        - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
                        - "--entrypoints=Name:https Address::443 TLS"
                        - "--defaultentrypoints=http,https"
                        - "--acme"
                        - "--acme.storage=acme.json"
                        - "--acme.entryPoint=https"
                        - "--acme.httpChallenge.entryPoint=http"
                        - "--acme.onHostRule=true"
                        - "--acme.onDemand=false"
                        - "--acme.email=test@zobalo.com"
                        - "--docker"
                        - "--docker.watch"
                network_mode: host
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
                        - /srv/traefik/acme/acme.json:/etc/traefik/acme.json           

        front:
                container_name: front
                restart: always
                image: paubarranca/debian-apache-php:latest
                volumes:
                        - /srv/apache2/web:/var/www/httpdocs
                labels:
                        - "traefik.frontend.rule=Host:dev.zobalo.com"
                        - "traefik.enable=true"
                        - "traefik.backend=front"
                        - "traefik.port=80"
        mysql:
                container_name: mysql
                restart: always
                image: mysql:5.7
                volumes:
                        - /srv/mysql/data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: RF772V9C4e5A6twPL
                        MYSQL_DATABASE: docker_test 
                        MYSQL_USER: docker-test
                        MYSQL_PASSWORD: sccG6Au8sGhHL
        wordpress:
                container_name: wordpress
                restart: always
                depends_on:
                        - mysql
                image: wordpress:php7.3-apache
                labels:
                        - "traefik.frontend.rule=Host:www.zobalo.com"
                        - "traefik.enable=true"
                        - "traefik.backend=wordpress"
                        - "traefik.port=80"
                volumes:
                        - /srv/wordpress/data:/var/www/html
                environment:
                        WORDPRESS_DB_HOST: mysql:3306
                        WORDPRESS_DB_USER: docker-test 
                        WORDPRESS_DB_PASSWORD: sccG6Au8sGhHL
                        WORDPRESS_DB_NAME: docker_test
        redis:
                container_name: redis
                restart: always
                depends_on:
                        - front
                image: redis
                ports:
                        - "6379:6379"
