version: '3'
services:
        haproxy:
                container_name: haproxy
                restart: always
                image: 'paubarranca/docker-multi-site-haproxy:latest'
                volumes:
                        - /srv/haproxy:/etc/haproxy 
                ports:
                        - "80:80"
                        - "443:443"
        front:
                container_name: front
                restart: always
                image: 'paubarranca/docker-multi-site-apache:latest'
                #volumes:
                #- /srv/apache2/sites-available:/etc/apache2/sites-available
                #- /srv/apache2/sites-enabled:/etc/apache2/sites-enabled
                #- /srv/web:/var/www/html
        mysql:
                container_name: mysql
                image: 'mysql'
                environment:
                        MYSQL_ROOT_PASSWORD: bdjfrdfief
        redis:
                image: 'redis:latest'
