version: '3'
services:
        haproxy:
                restart: always
                image: 'haproxy:latest'
                #volumes:
                        # - /srv/haproxy:/etc/haproxy 
                        # - /srv/haproxy/certs:/etc/haproxy/certs
                ports:
                        - "80:80"
                        - "443:443"
        nginx:
                restart: always
                image: 'nginx:latest'
                ports:
                        - '80:80'
        postgres:
                image: 'postgres:latest'
        redis:
                image: 'redis:latest'
