version: '3'
services:
        haproxy:
                container_name: haproxy
                restart: always
                image: 'paubarranca/docker-multi-site-haproxy:latest'
                volumes:
                        - /srv/haproxy:/etc/haproxy 
                        - /srv/haproxy/certs:/etc/haproxy/certs
                ports:
                        - "80:80"
                        - "443:443"
        nginx:
                container_name: nginx
                restart: always
                image: 'nginx:latest'
        mysql:
                container_name: mysql
                image: 'mysql'
                environment:
                        MYSQL_ROOT_PASSWORD: bdjfrdfief
        redis:
                image: 'redis:latest'
